function kcByChar(c){
  switch(kc) {
    case 65:
      return "A";
    case 73:
      return "I";
    case 85:
      return "U";
    case 69:
      return "E";
    case 79:
      return "O";
    case 75:
      return "K";
    case 83:
      return "S";
    case 84:
      return "T";
    case 78:
      return "N";
    case 72:
      return "H";
    case 77:
      return "M";
    case 89:
      return "Y";
    case 82:
      return "R";
    case 87:
      return "W";
    case 71:
      return "G";
    case 90:
      return "Z";
    case 74:
      return "J";
    case 68:
      return "D";
    case 66:
      return "B";
    case 86:
      return "V";
    case 80:
      return "P";
    case 70:
      return "F";
    case 81:
      return "Q";
    case 76:
      return "L";
    case 88:
      return "X";
    case 67:
      return "C";
    default:
      return 0;
  }
}
