function numByKcQwerty(kc){
  switch(kc) {
    case 65:
      return 42;
    case 73:
      return 36;
    case 85:
      return 35;
    case 69:
      return 31;
    case 79:
      return 37;
    case 75:
      return 49;
    case 83:
      return 43;
    case 84:
      return 33;
    case 78:
      return 60;
    case 72:
      return 47;
    case 77:
      return 61;
    case 89:
      return 34;
    case 82:
      return 32;
    case 87:
      return 30;
    case 71:
      return 46;
    case 90:
      return 55;
    case 74:
      return 48;
    case 68:
      return 44;
    case 66:
      return 59;
    case 86:
      return 58;
    case 80:
      return 38;
    case 70:
      return 45;
    case 81:
      return 29;
    case 76:
      return 50;
    case 88:
      return 56;
    case 67:
      return 57;
    default:
      return 0;
    }
}

function kcByNumQwerty(n){
  switch(n) {
     case 42:
      return 65
     case 36:
      return 73
     case 35:
      return 85
     case 31:
      return 69
     case 37:
      return 79
     case 49:
      return 75
     case 43:
      return 83
     case 33:
      return 84
     case 60:
      return 78
     case 47:
      return 72
     case 61:
      return 77
     case 34:
      return 89
     case 32:
      return 82
     case 30:
      return 87
     case 46:
      return 71
     case 55:
      return 90
     case 48:
      return 74
     case 44:
      return 68
     case 59:
      return 66
     case 58:
      return 86
     case 38:
      return 80
     case 45:
      return 70
     case 29:
      return 81
     case 50:
      return 76
     case 56:
      return 88
     case 57:
      return 67
    default:
      return 0;
    }
}

function kcByCharQwerty(c){
  switch(c) {
    case "A":
    case "a":
      return 65;
    case "I":
    case "i":
      return 73;
    case "U":
    case "u":
      return 85;
    case "E":
    case "e":
      return 69;
    case "O":
    case "o":
      return 79;
    case "K":
    case "k":
      return 75;
    case "S":
    case "s":
      return 83;
    case "T":
    case "t":
      return 84;
    case "N":
    case "n":
      return 78;
    case "H":
    case "h":
      return 72;
    case "M":
    case "m":
      return 77;
    case "Y":
    case "y":
      return 89;
    case "R":
    case "r":
      return 82;
    case "W":
    case "w":
      return 87;
    case "G":
    case "g":
      return 71;
    case "Z":
    case "z":
      return 90;
    case "J":
    case "j":
      return 74;
    case "D":
    case "d":
      return 68;
    case "B":
    case "b":
      return 66;
    case "V":
    case "v":
      return 86;
    case "P":
    case "p":
      return 80;
    case "F":
    case "f":
      return 70;
    case "Q":
    case "q":
      return 81;
    case "L":
    case "l":
      return 76;
    case "X":
    case "x":
      return 88;
    case "C":
    case "c":
      return 67;
    default:
        return 0;
  }
}

function charByKcQwerty(kc){
  switch(kc) {
    case 65:
      return "A";
    case 73:
      return "I";
    case 85:
      return "U";
    case 69:
      return "E";
    case 79:
      return "O";
    case 75:
      return "K";
    case 83:
      return "S";
    case 84:
      return "T";
    case 78:
      return "N";
    case 72:
      return "H";
    case 77:
      return "M";
    case 89:
      return "Y";
    case 82:
      return "R";
    case 87:
      return "W";
    case 71:
      return "G";
    case 90:
      return "Z";
    case 74:
      return "J";
    case 68:
      return "D";
    case 66:
      return "B";
    case 86:
      return "V";
    case 80:
      return "P";
    case 70:
      return "F";
    case 81:
      return "Q";
    case 76:
      return "L";
    case 88:
      return "X";
    case 67:
      return "C";
    default:
      return 0;
  }
}

function lCharByKcQwerty(kc){
  switch(kc) {
    case 65:
      return "a";
    case 73:
      return "i";
    case 85:
      return "u";
    case 69:
      return "e";
    case 79:
      return "o";
    case 75:
      return "k";
    case 83:
      return "s";
    case 84:
      return "t";
    case 78:
      return "n";
    case 72:
      return "h";
    case 77:
      return "m";
    case 89:
      return "y";
    case 82:
      return "r";
    case 87:
      return "w";
    case 71:
      return "g";
    case 90:
      return "z";
    case 74:
      return "j";
    case 68:
      return "d";
    case 66:
      return "b";
    case 86:
      return "v";
    case 80:
      return "p";
    case 70:
      return "f";
    case 81:
      return "q";
    case 76:
      return "l";
    case 88:
      return "x";
    case 67:
      return "c";
    default:
      return 0;
  }
}
